import type { CoursewareRecord, CoursewareSelectOption, CoursewareTypeFilter } from './courseware-workbench.types.ts'

export const currentCoursewareUploader = '林老师'

export const coursewareTypeOptions: CoursewareSelectOption<CoursewareTypeFilter>[] = [
  { value: 'all', label: '全部类型' },
  { value: 'PPT', label: 'PPT' },
  { value: 'PDF', label: 'PDF' },
  { value: 'DOC', label: 'DOC' },
]

export const coursewareRecords: CoursewareRecord[] = [
  {
    id: 'cw-1001',
    title: '第一章 计算机网络概述',
    course: '计算机网络',
    chapter: '第1章',
    type: 'PPT',
    fileSize: '2.5 MB',
    uploadedBy: currentCoursewareUploader,
    uploadedAt: '2026-04-12',
  },
  {
    id: 'cw-1002',
    title: '第二章 物理层',
    course: '计算机网络',
    chapter: '第2章',
    type: 'PPT',
    fileSize: '3.1 MB',
    uploadedBy: currentCoursewareUploader,
    uploadedAt: '2026-04-10',
  },
  {
    id: 'cw-1003',
    title: '第三章 数据链路层',
    course: '计算机网络',
    chapter: '第3章',
    type: 'PDF',
    fileSize: '1.9 MB',
    uploadedBy: currentCoursewareUploader,
    uploadedAt: '2026-04-08',
  },
  {
    id: 'cw-1004',
    title: '第四章 网络层',
    course: '计算机网络',
    chapter: '第4章',
    type: 'PPT',
    fileSize: '2.2 MB',
    uploadedBy: currentCoursewareUploader,
    uploadedAt: '2026-04-06',
  },
  {
    id: 'cw-1005',
    title: '数据结构导论',
    course: '数据结构',
    chapter: '第1章',
    type: 'PDF',
    fileSize: '1.8 MB',
    uploadedBy: currentCoursewareUploader,
    uploadedAt: '2026-04-04',
  },
  {
    id: 'cw-1006',
    title: '线性表实现',
    course: '数据结构',
    chapter: '第2章',
    type: 'PPT',
    fileSize: '2.1 MB',
    uploadedBy: currentCoursewareUploader,
    uploadedAt: '2026-04-03',
  },
  {
    id: 'cw-1007',
    title: '操作系统调度',
    course: '操作系统',
    chapter: '第4章',
    type: 'PPT',
    fileSize: '3.4 MB',
    uploadedBy: currentCoursewareUploader,
    uploadedAt: '2026-04-02',
  },
  {
    id: 'cw-1008',
    title: '数据库索引设计',
    course: '数据库系统',
    chapter: '第5章',
    type: 'PDF',
    fileSize: '2.6 MB',
    uploadedBy: currentCoursewareUploader,
    uploadedAt: '2026-03-30',
  },
  {
    id: 'cw-1009',
    title: 'Python 函数式编程',
    course: 'Python程序设计',
    chapter: '第6章',
    type: 'PPT',
    fileSize: '4.0 MB',
    uploadedBy: currentCoursewareUploader,
    uploadedAt: '2026-03-28',
  },
  {
    id: 'cw-1010',
    title: '软件测试基础',
    course: '软件工程',
    chapter: '第3章',
    type: 'DOC',
    fileSize: '1.3 MB',
    uploadedBy: currentCoursewareUploader,
    uploadedAt: '2026-03-20',
  },
]
