FROM node:22-alpine AS build
WORKDIR /build
COPY package.json .
RUN npm config set registry https://registry.npmmirror.com && npm install
COPY vite.config.ts tsconfig.json tsconfig.app.json tsconfig.node.json index.html ./
COPY src ./src
COPY public ./public
RUN npm run build-only

FROM nginx:alpine
COPY --from=build /build/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
