import type { VideoRecord } from './video-workbench.types.ts'

export const videoRecords: VideoRecord[] = [
  {
    id: 'video-1001',
    title: '计算机网络概述讲解',
    course: '计算机网络',
    chapter: '第1章',
    duration: '45:30',
    resolution: '1080p',
    viewCount: 234,
    uploadedBy: '张老师',
    uploadedAt: '2026-03-01',
    fileSize: '1.2GB',
    lastEditedAt: '2026-03-02 08:30',
    coverLabel: '课程导学',
    knowledgePoint: '网络分层模型',
    tags: ['导学', '基础'],
    description: '讲解计算机网络课程的整体结构与学习路径。',
    processingStatus: 'ready',
    publishStatus: 'draft',
    resourceAlert: null,
    assetId: null,
    coverAssetId: null,
    visibility: 'students',
    scheduledPublishAt: null,
  },
  {
    id: 'video-1002',
    title: '物理层知识点',
    course: '计算机网络',
    chapter: '第2章',
    duration: '38:15',
    resolution: '1080p',
    viewCount: 189,
    uploadedBy: '张老师',
    uploadedAt: '2026-03-05',
    fileSize: '980MB',
    lastEditedAt: '2026-03-05 14:20',
    coverLabel: '上传中',
    knowledgePoint: '信号与编码',
    tags: ['上传', '物理层'],
    description: '物理层核心概念的录屏视频，当前仍在上传处理中。',
    processingStatus: 'uploading',
    publishStatus: 'draft',
    resourceAlert: '上传中，等待资源处理完成后再发布。',
    assetId: null,
    coverAssetId: null,
    visibility: 'students',
    scheduledPublishAt: null,
  },
  {
    id: 'video-1003',
    title: '网络层知识点',
    course: '计算机网络',
    chapter: '第3章',
    duration: '52:00',
    resolution: '720p',
    viewCount: 312,
    uploadedBy: '李老师',
    uploadedAt: '2026-02-20',
    fileSize: '1.5GB',
    lastEditedAt: '2026-02-21 10:15',
    coverLabel: '转码中',
    knowledgePoint: '网络层转发原理',
    tags: ['转码', '网络层'],
    description: '讲解计算机网络第三章的核心概念，正在转码处理。',
    processingStatus: 'transcoding',
    publishStatus: 'published',
    resourceAlert: '转码中，处理完成后可继续发布。',
    assetId: null,
    coverAssetId: null,
    visibility: 'students',
    scheduledPublishAt: null,
  },
  {
    id: 'video-1004',
    title: '算法设计导论',
    course: '算法设计',
    chapter: '第2章',
    duration: '41:18',
    resolution: '1080p',
    viewCount: 455,
    uploadedBy: '王老师',
    uploadedAt: '2026-04-01',
    fileSize: '1.1GB',
    lastEditedAt: '2026-04-02 09:00',
    coverLabel: '已发布',
    knowledgePoint: '贪心算法',
    tags: ['发布', '算法'],
    description: '已上线的算法设计导论课，面向公开课程。',
    processingStatus: 'ready',
    publishStatus: 'published',
    resourceAlert: null,
    assetId: null,
    coverAssetId: null,
    visibility: 'students',
    scheduledPublishAt: '2026-04-03 09:00',
  },
  {
    id: 'video-1005',
    title: '操作系统实验课',
    course: '操作系统',
    chapter: '第3章',
    duration: '29:45',
    resolution: '1080p',
    viewCount: 98,
    uploadedBy: '王老师',
    uploadedAt: '2026-04-10',
    fileSize: '860MB',
    lastEditedAt: '2026-04-11 16:10',
    coverLabel: '离线',
    knowledgePoint: '进程调度',
    tags: ['离线', '实验'],
    description: '已下线的实验课视频，用于归档与复审。',
    processingStatus: 'ready',
    publishStatus: 'offline',
    resourceAlert: '该资源已下架，暂不可对外播放。',
    assetId: null,
    coverAssetId: null,
    visibility: 'internal',
    scheduledPublishAt: null,
  },
  {
    id: 'video-1006',
    title: '数据库索引原理',
    course: '数据库系统',
    chapter: '第1章',
    duration: '33:12',
    resolution: '720p',
    viewCount: 521,
    uploadedBy: '刘老师',
    uploadedAt: '2026-04-15',
    fileSize: '1.0GB',
    lastEditedAt: '2026-04-15 19:40',
    coverLabel: '失败',
    knowledgePoint: 'B+树索引',
    tags: ['失败', '索引'],
    description: '转码失败的视频资源，需要重新处理。',
    processingStatus: 'failed',
    publishStatus: 'draft',
    resourceAlert: '转码失败，请重新提交处理任务。',
    assetId: null,
    coverAssetId: null,
    visibility: 'students',
    scheduledPublishAt: null,
  },
  {
    id: 'video-1007',
    title: '软件工程需求分析',
    course: '软件工程',
    chapter: '第3章',
    duration: '48:05',
    resolution: '1080p',
    viewCount: 260,
    uploadedBy: '王老师',
    uploadedAt: '2026-04-20',
    fileSize: '1.3GB',
    lastEditedAt: '2026-04-21 11:25',
    coverLabel: '公开',
    knowledgePoint: '需求建模',
    tags: ['发布', '需求'],
    description: '已公开发布的软件工程课程视频。',
    processingStatus: 'ready',
    publishStatus: 'published',
    resourceAlert: null,
    assetId: null,
    coverAssetId: null,
    visibility: 'students',
    scheduledPublishAt: '2026-04-22 10:00',
  },
  {
    id: 'video-1008',
    title: '人工智能导论',
    course: '人工智能',
    chapter: '第4章',
    duration: '56:40',
    resolution: '1080p',
    viewCount: 612,
    uploadedBy: '赵老师',
    uploadedAt: '2026-04-25',
    fileSize: '1.7GB',
    lastEditedAt: '2026-04-26 13:00',
    coverLabel: '公开',
    knowledgePoint: '搜索与推理',
    tags: ['发布', 'AI'],
    description: '人工智能导论视频，已完成发布并供学生观看。',
    processingStatus: 'ready',
    publishStatus: 'published',
    resourceAlert: null,
    assetId: null,
    coverAssetId: null,
    visibility: 'students',
    scheduledPublishAt: '2026-04-27 09:00',
  },
]
