import type { OutlineCourseRecord, OutlineVersionSectionState } from './outline-workbench.types.ts'

function createBasicSections(overrides: Partial<OutlineVersionSectionState> = {}): OutlineVersionSectionState {
  return {
    basicInfo: {
      courseName: '',
      credits: 0,
      hours: 0,
      instructor: '',
      majors: [],
      ...overrides.basicInfo,
    },
    knowledgeGoals: overrides.knowledgeGoals ?? [],
    abilityGoals: overrides.abilityGoals ?? [],
    schedule: overrides.schedule ?? [],
    teachingMethods: {
      selected: [],
      notes: '',
      ...overrides.teachingMethods,
    },
    assessment: {
      usualPercentage: 0,
      midtermPercentage: 0,
      finalPercentage: 0,
      usualItems: [],
      notes: '',
      ...overrides.assessment,
    },
    materials: {
      primary: [],
      references: [],
      ...overrides.materials,
    },
  }
}

export const outlineTeachingMethodOptions = ['讲授', '讨论', '实验', '案例分析', '作业反馈', '专题汇报']

export const outlineWorkbenchCourses: OutlineCourseRecord[] = [
  {
    id: 'course-functions-and-derivatives',
    title: '函数与导数',
    instructor: '林知夏',
    department: '数学教研组',
    versions: [
      {
        id: 'outline-version-fd-2026-spring',
        courseId: 'course-functions-and-derivatives',
        versionName: '2026 春版',
        semester: '2026春',
        status: 'draft',
        archiveState: 'active',
        archivedAt: null,
        note: '面向新学期的一轮复习方案。',
        createdBy: '林知夏',
        updatedAt: '2026-04-10T09:30:00.000Z',
        updatedBy: '林知夏',
        sections: createBasicSections({
          basicInfo: {
            courseName: '函数与导数',
            credits: 4,
            hours: 64,
            instructor: '林知夏',
            majors: ['数学教育', '应用数学'],
          },
          knowledgeGoals: [{ id: 'fd-k-1', text: '理解函数、极限与导数的基本概念。' }],
          abilityGoals: [{ id: 'fd-a-1', text: '能够运用导数分析变化趋势并解决综合题。' }],
          schedule: [
            {
              id: 'fd-s-1',
              weekLabel: '第1周',
              topic: '函数与定义域',
              hours: 4,
              teachingMethod: '讲授+讨论',
              notes: '结合典型错题导入。',
              chapterLabel: '第一章',
            },
            {
              id: 'fd-s-2',
              weekLabel: '第2周',
              topic: '极限与连续',
              hours: 4,
              teachingMethod: '讲授+案例分析',
              notes: '加入图像判断训练。',
              chapterLabel: '第一章',
            },
            {
              id: 'fd-s-3',
              weekLabel: '第3周',
              topic: '导数概念与几何意义',
              hours: 4,
              teachingMethod: '讲授',
              notes: '强化切线问题。',
              chapterLabel: '第二章',
            },
            {
              id: 'fd-s-4',
              weekLabel: '第4周',
              topic: '导数应用',
              hours: 4,
              teachingMethod: '讲授+作业反馈',
              notes: '组织小测并讲评。',
              chapterLabel: '第二章',
            },
          ],
          teachingMethods: {
            selected: [],
            notes: '',
          },
          assessment: {
            usualPercentage: 30,
            midtermPercentage: 20,
            finalPercentage: 50,
            usualItems: [
              { id: 'fd-u-1', label: '作业', percentage: 20 },
              { id: 'fd-u-2', label: '课堂表现', percentage: 10 },
            ],
            notes: '采用阶段测评与期末综合考核。',
          },
          materials: {
            primary: [
              {
                id: 'fd-m-1',
                title: '高中数学必修（函数专题）',
                author: '课程组',
                source: '校本教材',
                note: '主教材',
              },
            ],
            references: [
              {
                id: 'fd-r-1',
                title: '导数题型精讲',
                author: '林知夏',
                source: '教研资料',
                note: '课后拓展',
              },
            ],
          },
        }),
      },
      {
        id: 'outline-version-fd-2026-review',
        courseId: 'course-functions-and-derivatives',
        versionName: '2026 二轮冲刺版',
        semester: '2026春',
        status: 'final',
        archiveState: 'active',
        archivedAt: null,
        note: '高考前冲刺使用。',
        createdBy: '林知夏',
        updatedAt: '2026-03-15T10:00:00.000Z',
        updatedBy: '林知夏',
        sections: createBasicSections({
          basicInfo: {
            courseName: '函数与导数',
            credits: 4,
            hours: 48,
            instructor: '林知夏',
            majors: ['数学教育'],
          },
          knowledgeGoals: [{ id: 'fd2-k-1', text: '巩固导数模型与函数综合题思路。' }],
          abilityGoals: [{ id: 'fd2-a-1', text: '在限时环境下完成函数压轴题拆解。' }],
          schedule: [
            {
              id: 'fd2-s-1',
              weekLabel: '第1周',
              topic: '导数综合题拆分策略',
              hours: 4,
              teachingMethod: '讲授+案例分析',
              notes: '配套限时训练。',
              chapterLabel: '冲刺一',
            },
            {
              id: 'fd2-s-2',
              weekLabel: '第2周',
              topic: '参数与不等式',
              hours: 4,
              teachingMethod: '讲授+讨论',
              notes: '强调边界分析。',
              chapterLabel: '冲刺二',
            },
          ],
          teachingMethods: {
            selected: ['讲授', '讨论'],
            notes: '采用例题精讲与当堂反馈结合。',
          },
          assessment: {
            usualPercentage: 40,
            midtermPercentage: 20,
            finalPercentage: 40,
            usualItems: [{ id: 'fd2-u-1', label: '限时训练', percentage: 20 }],
            notes: '每周一次专题测。',
          },
          materials: {
            primary: [
              {
                id: 'fd2-m-1',
                title: '函数与导数冲刺卷',
                author: '课程组',
                source: '校本题库',
                note: '',
              },
            ],
            references: [],
          },
        }),
      },
      {
        id: 'outline-version-fd-2025-fall',
        courseId: 'course-functions-and-derivatives',
        versionName: '2025 秋统整版',
        semester: '2025秋',
        status: 'final',
        archiveState: 'archived',
        archivedAt: '2025-12-20T10:00:00.000Z',
        note: '上一年度归档版本。',
        createdBy: '林知夏',
        updatedAt: '2025-09-01T10:00:00.000Z',
        updatedBy: '林知夏',
        sections: createBasicSections({
          basicInfo: {
            courseName: '函数与导数',
            credits: 4,
            hours: 64,
            instructor: '林知夏',
            majors: ['数学教育'],
          },
          knowledgeGoals: [{ id: 'fd3-k-1', text: '掌握函数与导数核心概念与计算方法。' }],
          abilityGoals: [{ id: 'fd3-a-1', text: '能够完成函数综合应用问题。' }],
          schedule: [
            {
              id: 'fd3-s-1',
              weekLabel: '第1周',
              topic: '函数基础',
              hours: 4,
              teachingMethod: '讲授',
              notes: '建立知识框架。',
              chapterLabel: '第一章',
            },
            {
              id: 'fd3-s-2',
              weekLabel: '第2周',
              topic: '极限与连续',
              hours: 4,
              teachingMethod: '讲授+讨论',
              notes: '组织分组练习。',
              chapterLabel: '第一章',
            },
            {
              id: 'fd3-s-3',
              weekLabel: '第3周',
              topic: '导数计算',
              hours: 4,
              teachingMethod: '讲授',
              notes: '强化计算规范。',
              chapterLabel: '第二章',
            },
            {
              id: 'fd3-s-4',
              weekLabel: '第4周',
              topic: '导数应用',
              hours: 4,
              teachingMethod: '讲授+作业反馈',
              notes: '完成章节测评。',
              chapterLabel: '第二章',
            },
          ],
          teachingMethods: {
            selected: ['讲授', '讨论', '作业反馈'],
            notes: '采用讲练结合模式。',
          },
          assessment: {
            usualPercentage: 30,
            midtermPercentage: 20,
            finalPercentage: 50,
            usualItems: [{ id: 'fd3-u-1', label: '作业', percentage: 20 }],
            notes: '执行教研组统一方案。',
          },
          materials: {
            primary: [
              {
                id: 'fd3-m-1',
                title: '函数与导数教学讲义',
                author: '数学教研组',
                source: '校本资料',
                note: '',
              },
            ],
            references: [],
          },
        }),
      },
      {
        id: 'outline-version-fd-2026-collab',
        courseId: 'course-functions-and-derivatives',
        versionName: '2026 协作试验版',
        semester: '2026春',
        status: 'draft',
        archiveState: 'active',
        archivedAt: null,
        note: '跨校协作版本，仅用于联合备课。',
        createdBy: '赵明远',
        updatedAt: '2026-04-01T09:00:00.000Z',
        updatedBy: '赵明远',
        sections: createBasicSections({
          basicInfo: {
            courseName: '函数与导数',
            credits: 4,
            hours: 32,
            instructor: '赵明远',
            majors: ['数学教育'],
          },
        }),
      },
    ],
  },
  {
    id: 'course-solid-geometry',
    title: '立体几何',
    instructor: '林知夏',
    department: '数学教研组',
    versions: [
      {
        id: 'outline-version-sg-2026-spring',
        courseId: 'course-solid-geometry',
        versionName: '2026 春版',
        semester: '2026春',
        status: 'final',
        archiveState: 'active',
        archivedAt: null,
        note: '核心专题版。',
        createdBy: '林知夏',
        updatedAt: '2026-03-25T08:20:00.000Z',
        updatedBy: '林知夏',
        sections: createBasicSections({
          basicInfo: {
            courseName: '立体几何',
            credits: 3,
            hours: 48,
            instructor: '林知夏',
            majors: ['数学教育'],
          },
          knowledgeGoals: [{ id: 'sg-k-1', text: '理解空间直线与平面的基本位置关系。' }],
          abilityGoals: [{ id: 'sg-a-1', text: '能够完成立体几何证明与计算题。' }],
          schedule: [
            {
              id: 'sg-s-1',
              weekLabel: '第1周',
              topic: '空间几何初步',
              hours: 4,
              teachingMethod: '讲授+讨论',
              notes: '建立空间想象能力。',
              chapterLabel: '第一章',
            },
          ],
          teachingMethods: {
            selected: ['讲授', '讨论'],
            notes: '使用模型演示辅助讲解。',
          },
          assessment: {
            usualPercentage: 30,
            midtermPercentage: 20,
            finalPercentage: 50,
            usualItems: [{ id: 'sg-u-1', label: '作业', percentage: 15 }],
            notes: '',
          },
          materials: {
            primary: [
              {
                id: 'sg-m-1',
                title: '立体几何专题讲义',
                author: '林知夏',
                source: '校本资料',
                note: '',
              },
            ],
            references: [],
          },
        }),
      },
    ],
  },
  {
    id: 'course-data-structure',
    title: '概率与统计',
    instructor: '周晨',
    department: '统计教研组',
    versions: [
      {
        id: 'outline-version-ds-2026-fall',
        courseId: 'course-data-structure',
        versionName: '2026 秋版',
        semester: '2026秋',
        status: 'final',
        archiveState: 'active',
        archivedAt: null,
        note: '跨校协作版本。',
        createdBy: '周晨',
        updatedAt: '2026-03-12T15:20:00.000Z',
        updatedBy: '周晨',
        sections: createBasicSections({
          basicInfo: {
            courseName: '概率与统计',
            credits: 4,
            hours: 64,
            instructor: '周晨',
            majors: ['应用统计'],
          },
          knowledgeGoals: [{ id: 'ps-k-1', text: '掌握随机变量与分布的核心概念。' }],
          abilityGoals: [{ id: 'ps-a-1', text: '能够完成常见统计推断任务。' }],
          schedule: [
            {
              id: 'ps-s-1',
              weekLabel: '第1周',
              topic: '随机事件与概率',
              hours: 4,
              teachingMethod: '讲授',
              notes: '',
              chapterLabel: '第一章',
            },
          ],
          teachingMethods: {
            selected: ['讲授'],
            notes: '',
          },
          assessment: {
            usualPercentage: 40,
            midtermPercentage: 20,
            finalPercentage: 40,
            usualItems: [{ id: 'ps-u-1', label: '实验', percentage: 20 }],
            notes: '',
          },
          materials: {
            primary: [
              {
                id: 'ps-m-1',
                title: '概率论与数理统计',
                author: '盛骤',
                source: '高等教育出版社',
                note: '',
              },
            ],
            references: [],
          },
        }),
      },
    ],
  },
]
