import type { OutlineCourseRecord, OutlineVersionSectionState } from './outline-workbench.types.ts'

function createBasicSections(overrides: Partial<OutlineVersionSectionState> = {}): OutlineVersionSectionState {
  return {
    basicInfo: {
      courseName: '',
      credits: 0,
      hours: 0,
      instructor: '',
      majors: [],
      ...overrides.basicInfo,
    },
    knowledgeGoals: overrides.knowledgeGoals ?? [],
    abilityGoals: overrides.abilityGoals ?? [],
    schedule: overrides.schedule ?? [],
    teachingMethods: {
      selected: [],
      notes: '',
      ...overrides.teachingMethods,
    },
    assessment: {
      usualPercentage: 0,
      midtermPercentage: 0,
      finalPercentage: 0,
      usualItems: [],
      notes: '',
      ...overrides.assessment,
    },
    materials: {
      primary: [],
      references: [],
      ...overrides.materials,
    },
  }
}

export const outlineTeachingMethodOptions = ['讲授', '讨论', '实验', '案例分析', '作业反馈', '专题汇报']

export const outlineWorkbenchCourses: OutlineCourseRecord[] = [
  {
    id: 'course-advanced-mathematics',
    title: '高等数学',
    instructor: '王老师',
    department: '数学教研室',
    versions: [
      {
        id: 'outline-version-amath-2026-spring',
        courseId: 'course-advanced-mathematics',
        versionName: '2026 春版',
        semester: '2026春',
        status: 'draft',
        archiveState: 'active',
        archivedAt: null,
        note: '',
        updatedAt: '2026-04-10T09:30:00.000Z',
        updatedBy: '王老师',
        sections: createBasicSections({
          basicInfo: {
            courseName: '高等数学',
            credits: 5,
            hours: 80,
            instructor: '王老师',
            majors: ['机械工程', '自动化'],
          },
          knowledgeGoals: [
            { id: 'goal-k-1', text: '理解函数、极限、导数与积分的基本概念。' },
            { id: 'goal-k-2', text: '掌握高等数学主要定理与典型计算方法。' },
          ],
          abilityGoals: [{ id: 'goal-a-1', text: '能够用微积分方法分析工程中的变化规律。' }],
          schedule: [
            {
              id: 'schedule-1',
              weekLabel: '第1周',
              topic: '函数与极限',
              hours: 4,
              teachingMethod: '讲授+讨论',
              notes: '安排课后导学作业。',
              chapterLabel: '第1章',
            },
            {
              id: 'schedule-2',
              weekLabel: '第2周',
              topic: '导数与微分',
              hours: 4,
              teachingMethod: '讲授+案例分析',
              notes: '结合速度变化案例。',
              chapterLabel: '第2章',
            },
            {
              id: 'schedule-3',
              weekLabel: '第3周',
              topic: '导数应用',
              hours: 4,
              teachingMethod: '讲授+作业反馈',
              notes: '引入最值问题。',
              chapterLabel: '第3章',
            },
            {
              id: 'schedule-4',
              weekLabel: '第4周',
              topic: '不定积分',
              hours: 4,
              teachingMethod: '讲授',
              notes: '配套例题精讲。',
              chapterLabel: '第4章',
            },
          ],
          teachingMethods: {
            selected: ['讲授', '讨论', '案例分析', '作业反馈'],
            notes: '强调课堂推导、例题演示与习题反馈的闭环。',
          },
          assessment: {
            usualPercentage: 30,
            midtermPercentage: 20,
            finalPercentage: 60,
            usualItems: [
              { id: 'usual-1', label: '作业', percentage: 15 },
              { id: 'usual-2', label: '考勤', percentage: 5 },
              { id: 'usual-3', label: '课堂表现', percentage: 10 },
            ],
            notes: '期末闭卷考试为主。',
          },
          materials: {
            primary: [
              {
                id: 'material-1',
                title: '高等数学（上册）',
                author: '同济大学数学系',
                source: '高等教育出版社',
                note: '主教材',
              },
            ],
            references: [
              {
                id: 'reference-1',
                title: '高等数学辅导讲义',
                author: '教研室自编',
                source: '院内资料',
                note: '配套习题讲解',
              },
            ],
          },
        }),
      },
      {
        id: 'outline-version-amath-2025-fall',
        courseId: 'course-advanced-mathematics',
        versionName: '2025 秋版',
        semester: '2025秋',
        status: 'final',
        archiveState: 'archived',
        archivedAt: '2025-12-20T10:00:00.000Z',
        note: '2025 级培养方案正式版。',
        updatedAt: '2025-09-01T10:00:00.000Z',
        updatedBy: '王老师',
        sections: createBasicSections({
          basicInfo: {
            courseName: '高等数学',
            credits: 5,
            hours: 80,
            instructor: '王老师',
            majors: ['机械工程', '自动化'],
          },
          knowledgeGoals: [{ id: 'goal-k-2025-1', text: '掌握极限、导数与积分的基础理论。' }],
          abilityGoals: [{ id: 'goal-a-2025-1', text: '能够解决一元函数微积分基础问题。' }],
          schedule: [
            {
              id: 's-2025-1',
              weekLabel: '第1周',
              topic: '函数与极限',
              hours: 4,
              teachingMethod: '讲授',
              notes: '导学安排。',
              chapterLabel: '第1章',
            },
            {
              id: 's-2025-2',
              weekLabel: '第2周',
              topic: '连续与导数',
              hours: 4,
              teachingMethod: '讲授+讨论',
              notes: '课堂练习。',
              chapterLabel: '第2章',
            },
            {
              id: 's-2025-3',
              weekLabel: '第3周',
              topic: '积分应用',
              hours: 4,
              teachingMethod: '讲授',
              notes: '例题精讲。',
              chapterLabel: '第3章',
            },
            {
              id: 's-2025-4',
              weekLabel: '第4周',
              topic: '微分方程初步',
              hours: 4,
              teachingMethod: '讲授',
              notes: '章节测验。',
              chapterLabel: '第4章',
            },
          ],
          teachingMethods: {
            selected: ['讲授', '讨论', '作业反馈'],
            notes: '坚持例题驱动与周周作业。',
          },
          assessment: {
            usualPercentage: 40,
            midtermPercentage: 20,
            finalPercentage: 40,
            usualItems: [
              { id: 'u-2025-1', label: '作业', percentage: 20 },
              { id: 'u-2025-2', label: '考勤', percentage: 10 },
              { id: 'u-2025-3', label: '课堂表现', percentage: 10 },
            ],
            notes: '按学院统一方案执行。',
          },
          materials: {
            primary: [
              {
                id: 'm-2025-1',
                title: '高等数学（上册）',
                author: '同济大学数学系',
                source: '高等教育出版社',
                note: '',
              },
            ],
            references: [],
          },
        }),
      },
    ],
  },
  {
    id: 'course-data-structure',
    title: '数据结构',
    instructor: '李老师',
    department: '计算机基础教研室',
    versions: [
      {
        id: 'outline-version-ds-2026-fall',
        courseId: 'course-data-structure',
        versionName: '2026 秋版',
        semester: '2026秋',
        status: 'final',
        archiveState: 'active',
        archivedAt: null,
        note: '实验环节与课堂讲授并行版。',
        updatedAt: '2026-03-12T15:20:00.000Z',
        updatedBy: '李老师',
        sections: createBasicSections({
          basicInfo: {
            courseName: '数据结构',
            credits: 4,
            hours: 64,
            instructor: '李老师',
            majors: ['计算机科学与技术', '软件工程'],
          },
          knowledgeGoals: [{ id: 'ds-k-1', text: '理解线性结构、树与图的基本原理。' }],
          abilityGoals: [{ id: 'ds-a-1', text: '能够完成典型数据结构的实现与复杂度分析。' }],
          schedule: [
            {
              id: 'ds-s-1',
              weekLabel: '第1周',
              topic: '线性表',
              hours: 4,
              teachingMethod: '讲授+实验',
              notes: '完成顺序表实验。',
              chapterLabel: '第1章',
            },
            {
              id: 'ds-s-2',
              weekLabel: '第2周',
              topic: '栈与队列',
              hours: 4,
              teachingMethod: '讲授+实验',
              notes: '布置上机作业。',
              chapterLabel: '第2章',
            },
            {
              id: 'ds-s-3',
              weekLabel: '第3周',
              topic: '树与二叉树',
              hours: 4,
              teachingMethod: '讲授+讨论',
              notes: '算法分析训练。',
              chapterLabel: '第3章',
            },
            {
              id: 'ds-s-4',
              weekLabel: '第4周',
              topic: '图',
              hours: 4,
              teachingMethod: '讲授+案例分析',
              notes: '结合路径问题。',
              chapterLabel: '第4章',
            },
          ],
          teachingMethods: {
            selected: ['讲授', '实验', '讨论', '案例分析'],
            notes: '每章配一节实验与一次代码讲评。',
          },
          assessment: {
            usualPercentage: 40,
            midtermPercentage: 20,
            finalPercentage: 40,
            usualItems: [
              { id: 'ds-u-1', label: '作业', percentage: 10 },
              { id: 'ds-u-2', label: '实验', percentage: 20 },
              { id: 'ds-u-3', label: '考勤', percentage: 10 },
            ],
            notes: '期末机考与笔试结合。',
          },
          materials: {
            primary: [
              {
                id: 'ds-m-1',
                title: '数据结构（C语言版）',
                author: '严蔚敏',
                source: '清华大学出版社',
                note: '',
              },
            ],
            references: [
              {
                id: 'ds-r-1',
                title: 'LeetCode 题单',
                author: '在线资源',
                source: 'LeetCode',
                note: '用于课后拓展',
              },
            ],
          },
        }),
      },
    ],
  },
  {
    id: 'course-discrete-mathematics',
    title: '离散数学',
    instructor: '周老师',
    department: '计算机基础教研室',
    versions: [
      {
        id: 'outline-version-dm-2026-fall',
        courseId: 'course-discrete-mathematics',
        versionName: '2026 秋版',
        semester: '2026秋',
        status: 'draft',
        archiveState: 'active',
        archivedAt: null,
        note: '待补齐参考资料与考核细则。',
        updatedAt: '2026-03-20T08:15:00.000Z',
        updatedBy: '周老师',
        sections: createBasicSections({
          basicInfo: {
            courseName: '离散数学',
            credits: 3,
            hours: 48,
            instructor: '周老师',
            majors: ['软件工程'],
          },
          knowledgeGoals: [{ id: 'dm-k-1', text: '理解命题逻辑、集合与关系。' }],
          abilityGoals: [],
          schedule: [
            {
              id: 'dm-s-1',
              weekLabel: '第1周',
              topic: '命题逻辑',
              hours: 4,
              teachingMethod: '讲授',
              notes: '基础概念导入。',
              chapterLabel: '第1章',
            },
          ],
          teachingMethods: {
            selected: ['讲授'],
            notes: '',
          },
          assessment: {
            usualPercentage: 20,
            midtermPercentage: 20,
            finalPercentage: 60,
            usualItems: [{ id: 'dm-u-1', label: '作业', percentage: 10 }],
            notes: '',
          },
          materials: {
            primary: [],
            references: [],
          },
        }),
      },
    ],
  },
]
