import type { MappingRecord } from './mapping-workbench.types.ts'

export const mappingRecords: MappingRecord[] = [
  {
    id: 'map-1001',
    resourceTitle: 'OSI 分层导读',
    resourceType: 'article',
    courseName: '计算机网络',
    chapterName: '第1章 体系结构',
    batchId: 'batch-2026-01',
    batchLabel: '2026 春季第一批',
    reviewStatus: 'pending',
    confidenceLevel: 'medium',
    primaryKnowledgePoint: null,
    selectedCandidateId: null,
    candidates: [
      {
        id: 'cand-1001-a',
        knowledgePointName: 'OSI 分层模型',
        confidenceLevel: 'medium',
        matchedBy: 'ai',
        note: '根据标题与章节语义匹配得出。',
      },
      {
        id: 'cand-1001-b',
        knowledgePointName: '网络体系结构',
        confidenceLevel: 'low',
        matchedBy: 'ai',
        note: '候选范围较宽，需要人工确认。',
      },
    ],
  },
  {
    id: 'map-1002',
    resourceTitle: '路由算法课件',
    resourceType: 'courseware',
    courseName: '计算机网络',
    chapterName: '第4章 路由选择',
    batchId: 'batch-2026-01',
    batchLabel: '2026 春季第一批',
    reviewStatus: 'pending',
    confidenceLevel: 'high',
    primaryKnowledgePoint: null,
    selectedCandidateId: 'cand-1002-a',
    candidates: [
      {
        id: 'cand-1002-a',
        knowledgePointName: '路由算法',
        confidenceLevel: 'high',
        matchedBy: 'ai',
        note: '课件标题与知识点完全一致。',
      },
      {
        id: 'cand-1002-b',
        knowledgePointName: '最短路径计算',
        confidenceLevel: 'medium',
        matchedBy: 'ai',
        note: '关联到路由计算细分知识点。',
      },
    ],
  },
  {
    id: 'map-1003',
    resourceTitle: 'IP 地址划分选择题',
    resourceType: 'question',
    courseName: '计算机网络',
    chapterName: '第3章 网络层基础',
    batchId: 'batch-2026-02',
    batchLabel: '2026 春季第二批',
    reviewStatus: 'approved',
    confidenceLevel: 'high',
    primaryKnowledgePoint: 'IP 地址划分',
    selectedCandidateId: 'cand-1003-a',
    candidates: [
      {
        id: 'cand-1003-a',
        knowledgePointName: 'IP 地址划分',
        confidenceLevel: 'high',
        matchedBy: 'manual',
        note: '题干与答案解析已由老师确认。',
      },
    ],
  },
  {
    id: 'map-1004',
    resourceTitle: '编程实验录屏',
    resourceType: 'video',
    courseName: '程序设计基础',
    chapterName: '第6章 实验实践',
    batchId: 'batch-2026-03',
    batchLabel: '2026 春季第三批',
    reviewStatus: 'pending',
    confidenceLevel: 'low',
    primaryKnowledgePoint: null,
    selectedCandidateId: 'cand-1004-a',
    candidates: [
      {
        id: 'cand-1004-a',
        knowledgePointName: '编程实验',
        confidenceLevel: 'low',
        matchedBy: 'ai',
        note: '录屏内容跨度较大，建议人工复核。',
      },
      {
        id: 'cand-1004-b',
        knowledgePointName: '程序调试',
        confidenceLevel: 'low',
        matchedBy: 'ai',
        note: '次要候选，缺少足够上下文。',
      },
    ],
  },
  {
    id: 'map-1005',
    resourceTitle: '数据库事务节选',
    resourceType: 'excerpt',
    courseName: '数据库系统',
    chapterName: '第5章 事务管理',
    batchId: 'batch-2026-03',
    batchLabel: '2026 春季第三批',
    reviewStatus: 'rejected',
    confidenceLevel: 'low',
    primaryKnowledgePoint: null,
    selectedCandidateId: null,
    candidates: [
      {
        id: 'cand-1005-a',
        knowledgePointName: '事务隔离级别',
        confidenceLevel: 'low',
        matchedBy: 'ai',
        note: '节选内容不完整，当前无法稳定确认。',
      },
    ],
  },
]
